version: '3.4'

services:
  ms-sql-server:
    image: mcr.microsoft.com/mssql/server:2019-CU16-GDR1-ubuntu-20.04
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: ${DB_PASSWORD}
    ports:
      - "1433:1433"
  tasktrackerapi:
    image: tasktrackerapi
    build:
      context: .
      dockerfile: TaskTracker.Api/Dockerfile
    ports:
      - 8080:80
    depends_on:
      - ms-sql-server
    environment:
      DB_SERVER: ms-sql-server
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}